Run Kobiton Automation Test on CircleCI
kobiton/CircleCI-HockeyApp-Appium-ReactNative pull request #3
Opened 2018-09-06 04:38 UTC by blackheat

2018-09-06 08:55 UTC, baotn166 requested changes
@blackheat Please consider my comments and fix if you see that make sense.

2018-09-06 08:55 UTC, baotn166 commented on Integrate-Kobiton.md
> +    > If your don't have one, go to https://portal.kobiton.com/register to create an account.
* Typo mistake: `If your don't have one`, `your` -> `you`.
* I don't think we should have quote `>` for this content.

2018-09-06 08:55 UTC, baotn166 commented on Integrate-Kobiton.md
> +Link to the sample : [https://github.com/kobiton/CircleCI-HockeyApp-Appium-ReactNative/tree/master/sample](https://github.com/kobiton/CircleCI-HockeyApp-Appium-ReactNative/tree/master/sample)
* `Link to the sample :` -> `Link to the sample:`

2018-09-06 08:55 UTC, baotn166 commented on Integrate-Kobiton.md
> +In order to use the provided sample, follow these steps
Put colon (:) at the end of this sentence: `In order to use the provided sample, follow these steps:`

2018-09-06 08:55 UTC, baotn166 commented on Integrate-Kobiton.md
> +2. Copy contents of `sample` folder into your repository.
Which is my repository? Please describe more details.

2018-09-06 08:55 UTC, baotn166 commented on Integrate-Kobiton.md
> +2. Copy contents of `sample` folder into your repository.
Please read this [content](https://github.com/kobiton/Travis-HockeyApp-Appium-ReactNative/blob/fad49be7d621fa99d0bbcc792d79bd448432f602/integrate-kobiton-travisci.md#1-prerequisites) from Thang and fix your content for clearer.

2018-09-06 08:55 UTC, baotn166 commented on Integrate-Kobiton.md
> +    > If your don't have one, go to https://portal.kobiton.com/register to create an account.
`Prerequisites` section just have one item, are you sure?

2018-09-06 08:55 UTC, baotn166 commented on Integrate-Kobiton.md
> +### 1. Getting required parameters
Why `required parameters` are showing here, do you understand what does `Prerequisites` mean?

2018-09-06 08:55 UTC, baotn166 commented on Integrate-Kobiton.md
> +### 1. Getting required parameters
Move this section to `Prerequisites`

2018-09-06 08:55 UTC, baotn166 commented on Integrate-Kobiton.md
> +
We should describe a little bit parameters (which is required or not):
* YOUR_APP_URL: (app repo or external link)
* DEVICE_NAME
* PLATFORM_VERSION
* PLATFORM_NAME

2018-09-06 08:55 UTC, baotn166 commented on Integrate-Kobiton.md
> +Simply push all changes to your repository and CircleCI will automatically execute the test script.
What are all changes? Please tell clearer.

2018-09-06 08:55 UTC, baotn166 commented on Integrate-Kobiton.md
> +Simply push all changes to your repository and CircleCI will automatically execute the test script.
How will CircleCI execute the test script automatically? Please describe a little bit about `.circleci/config.yml`, where is the place to put it in and how it works (stages, commands).

2018-09-10 10:47 UTC, thangvo38 requested changes
Please take a look

2018-09-10 10:47 UTC, thangvo38 commented on .gitignore
> +node_modules
`node_modules` -> `node_modules/`
This will ignore all directories named `node_modules` in folders and subfolders

2018-09-10 10:47 UTC, thangvo38 commented on Integrate-Kobiton.md
> +3. Follow next sections to get desired capabilities and configure all necessary variables for running automation test.
Replace this with `Clone the forked repo and <do stuff>` because the user must clone the repo in order to edit the scripts.

2018-09-10 10:47 UTC, thangvo38 commented on Integrate-Kobiton.md
> +![Automation Settings](./assets/desired-caps.png)
Replace this image where we only highlight the `desiredCaps` in blue.
Visit my repo for the image file.

2018-09-10 10:47 UTC, thangvo38 commented on Integrate-Kobiton.md
> +2. Replace `<SCRIPT_FILENAME>` with `android-app-test` if you want to execute automation test on Android or `ios-app-test` if on iOS.
Please show `a part` of the yml file where you make this replacement.

2018-09-11 06:08 UTC, tiennguyenhoan requested changes
@blackheat Please take a look

2018-09-11 06:08 UTC, tiennguyenhoan commented on Integrate-Kobiton.md
> +Kobiton Username and API key are required for authenticating with Kobiton REST API.
You are guiding users to execute automation test, so what is the relation between automation test and REST API ?

2018-09-11 06:08 UTC, tiennguyenhoan commented on Integrate-Kobiton.md
> +5. Write down the generated code as we will be using it later.
Remove this line, I think this isn't necessary

2018-09-11 06:08 UTC, NguyenHoanTien commented on Integrate-Kobiton.md
> +In the `samples` folder, we have provided two sample scripts for executing automation test on Kobiton iOS and Android devices. In those provided scripts, we will be executing automation testing of `A
"In those provided scripts, we will be executing automation testing of `ApiDemos-debug` application on Android and `UIKitCatalog-Test-Adhoc` application on iOS." I think this is a distraction information, remove this

2018-09-11 06:08 UTC, NguyenHoanTien commented on Integrate-Kobiton.md
> +```yaml
How about we provide somethings like this: 
Suggestion: 

```
2. Replace `<SCRIPT_FILENAME>` with the tested file before execute automation. 
 - To run automation test on Android devices
run:
    name: app-auto-testing
    command: npm run android-app-test.js
    working_directory: samples

 - To run automation test on iOS devices
run:
    name: app-auto-testing
    command: npm run ios-app-test.js
    working_directory: samples
```

2018-09-11 06:08 UTC, NguyenHoanTien commented on Integrate-Kobiton.md
> +**Modifying the configuration file to execute the automation test script**
I think this part should be the first part of this session. 

```
3. Configuring automation test script

3.1 Configuration .circleCI to execute automation test script
- Execution environment
- Modifying the configuration file to execute the automation test script

3.2 Configuring automation test script
```

Remember to ask user to choose the file that they choose when they modify the configuration file

2018-09-14 03:40 UTC, tiennguyenhoan requested changes
@blackheat please referencing comments from travis PR

2018-09-14 03:40 UTC, tiennguyenhoan commented on README.md
> +4. Clone the forked repository as we will be modifying it later.
```
1.
2.
4. 
```

2018-09-14 07:21 UTC, tiennguyenhoan requested changes
@blackheat please take a look

2018-09-14 07:21 UTC, tiennguyenhoan commented on README.md
> +Link to the sample(s): https://github.com/kobiton/CircleCI-HockeyApp-Appium-ReactNative/tree/master/samples
```
Link to the sample(s) folder:
```

2018-09-14 07:21 UTC, tiennguyenhoan commented on README.md
> +In this guide, as we will be using the provided example, therefore, follow these steps below:
```
**Note:** We will use the **sample** in this repo to demonstrate, follow steps below before started
```

2018-09-14 07:21 UTC, tiennguyenhoan commented on README.md
> +3. Clone the forked repository as we will be modifying it later.
"as" >> "and" ???

2018-09-14 07:21 UTC, tiennguyenhoan commented on README.md
> +In order to interact with a specific device in Kobiton, its corresponding desired capabilities needs to be supplied. In this example, we will be demonstrating how to get desired capabilities to execu
```
In order to interact with a specific device in Kobiton, its corresponding desired capabilities needs to be supplied.

In this example, we will use android devices `Pixel 2 XL` with version `8.1.0` to demonstrate automation test, and you can use  `ApiDemos-debug` app as a sample.
- App url: https://appium.github.io/appium/docs/assets/ApiDemos-debug.apk

**Note:** If you want to test with iOS devices, you can follow the steps below as reference and use the sample app : `UIKitCatalog-Test-Adhoc`
- App url: https://s3-ap-southeast-1.amazonaws.com/kobiton-devvn/apps-test/UIKitCatalog-Test-Adhoc.ipa

```

2018-09-14 07:21 UTC, tiennguyenhoan commented on README.md
> +4. In the popup window:
```
4. Get devices desiredCaps
```

2018-09-14 07:21 UTC, tiennguyenhoan commented on README.md
> +To demonstrate automation testing on iOS, repeat above steps with an iOS device (in this example, we will be using `iPhone 8 Plus` running `iOS 11.0`) and replace the `Application URL` field with the
Remove this part

2018-09-14 07:21 UTC, tiennguyenhoan commented on README.md
> +In `samples/automation-test` folder, we have provided two sample scripts for executing automation test on Kobiton iOS and Android devices.
To execute automation test, please go to  `[samples/automation-test](link)` folder

1. Open the test script as the devices platform you have selected to get `desiredCap`
     - Android: android-app-test.js
    - iOS: iOS-app-test.js

2. Replace desiredCaps value with the one taken above.

Here is the desired caps from example above. With other devices or other platform may have the different value, so make sure double check before adding to the script.
```
const desiredCaps = {
  sessionName:        'Automation test session',
  sessionDescription: 'Demo Automation Test on Android', 
  deviceOrientation:  'portrait',  
  captureScreenshots: true, 
  app:                'https://appium.github.io/appium/docs/assets/ApiDemos-debug.apk',
  deviceGroup:        'KOBITON', 
  deviceName:         'Pixel 2 XL',
  platformVersion:    '8.1.0',
  platformName:       'Android' 
}
```

2018-09-14 10:23 UTC, tiennguyenhoan approved these changes

2018-11-05 11:36 UTC, NguyenHoanTien commented
@blackheat Since this PR has been out of date, please close this PR

2018-11-06 02:29 UTC, closed without merging